DEFAULT_SEQUENCE_LENGTH = 256
DEFAULT_TRAIN_SAMPLES = 2048
DEFAULT_VAL_SAMPLES = 512
DEFAULT_TEST_SAMPLES = 512

DEFAULT_BATCH_SIZE = 64
DEFAULT_EPOCHS = 20
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_BOTTLENECK_DIM = 32
DEFAULT_HIDDEN_DIM = 128
DEFAULT_NUM_LAYERS = 1

DEFAULT_GAUSSIAN_STD = 0.15
DEFAULT_MASK_RATIO = 0.15
DEFAULT_MASK_MIN_LENGTH = 4
DEFAULT_MASK_MAX_LENGTH = 16

DEFAULT_SEED = 42
